services:
  db:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_user
      - db_name
      - root_db_password
    networks:
      - proxy
  app1:
    image: ghcr.io/y-l-g/app1:main
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_user
      - db_name
      - root_db_password
    networks:
      - proxy
volumes:
  caddy_data:
  caddy_config:
  todo-mysql-data:
networks:
  proxy:
    external: true
secrets:
  db_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true
  root_db_password:
    external: true
