services:
  db:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/app1_root_db_password
      MYSQL_DATABASE_FILE: /run/secrets/app1_db_name
      MYSQL_USER_FILE: /run/secrets/app1_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/app1_db_password
    secrets:
      - app1_db_password
      - app1_db_user
      - app1_db_name
      - app1_root_db_password
  app:
    image: ghcr.io/y-l-g/app1:main
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/app1_db_name
      MYSQL_USER_FILE: /run/secrets/app1_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/app1_db_password
    secrets:
      - app1_db_password
      - app1_db_user
      - app1_db_name
    networks:
      - proxy
volumes:
  caddy_data:
  caddy_config:
  todo-mysql-data:
networks:
  proxy:
    external: true
secrets:
  app1_db_password:
    external: true
  app1_db_user:
    external: true
  app1_db_name:
    external: true
  app1_root_db_password:
    external: true
