services:
  db:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - proxy
  app:
    develop:
      watch:
        - path: ./public
          action: sync
          target: /app/public
    build: .
    image: localhost:6000/app1
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/app/public
    networks:
      - proxy
volumes:
  caddy_data:
  caddy_config:
  todo-mysql-data:
networks:
  proxy:
    external: true
