services:
  app:
    image: ghcr.io/y-l-g/app1:main
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      MYSQL_USER_FILE: /run/secrets/database_user
      MYSQL_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - database_user
      - database_password
    networks:
      - app1
volumes:
  caddy_data:
  caddy_config:
networks:
  app1:
    driver: overlay
    attachable: true
secrets:
  database_password:
    external: true
  database_user:
    external: true
